machine:

  environment:

    USER_NAME: TanapatLimsombat

    USER_EMAIL: tem@iglu.net

  ruby:

    version: 2.3.1



dependencies:

  pre:

    - ./bin/setup



test:

  post:

    - bundle exec jekyll build

    - bundle exec htmlproofer ./_site --only-4xx --allow-hash-href



deployment:

  production:

    branch: master

    commands:

      - ./bin/automated
assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

ga_analytics: # Add Google Analytics tracking code

gems:
  - jekyll-assets
  - jekyll-sitemap

name: ccitest

permalink: pretty

url: # Add your site url
